
log:
  writers: stdout              # 输出位置，有两个可选项 —— file 和 stdout。选择 file 会将日志记录到 logger_file 指定的日志文件中，选择 stdout 会将日志输出到标准输出，当然也可以两者同时选择
  logger_level: DEBUG           # 日志级别，DEBUG、INFO、WARN、ERROR、FATAL
  logger_dir: log              # 日志文件目录
  log_rotate_date: 1           # rotate 转存时间
  log_rotate_size: 1           # rotate 转存大小

port:
#  - 80
  - 801

#tls:
#  - port: 4433
#    cert: cert/cdnbye.pem
#    key: cert/cdnbye.key

ratelimit:
  enable: true
  max_rate: 400                # max requests per second

stats:
  enable: true

compression:
  enable: false

security:
  enable: true                # Enable Authentication
  maxTimeStampAge: 3600        # Timestamp expiration time in seconds
  token: "example"              # Custom token, no more than 8 characters




